// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.819
package web

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func (w *Web) help() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<h1>Help - CodeCowboy 🤠</h1><p>Welcome to Code Cowboy! This web interface helps you manage your classrooms, import student data, and run autograding for assignments. Below is an overview of the main sections of the site and a quick guide to grading your first class. </p><h2>Navigation Overview</h2><p>The Code Cowboy web interface provides the following main sections:</p><h4>Courses</h4><p>The Courses page displays all of your created classrooms. Clicking on a classroom navigates you to the that classrooms detail page.</p><h4>Import</h4><p>The Import page allows you to create a new course by uploading student data from Canvas and GitHub Classroom. The provided form requires: </p><ul><li>Course Name</li><li>GitHub Classroom CSV File</li><li>Canvas CSV File</li><li>Assignment list JSON File</li></ul><h4>DB Utils</h4><p>The DB Utils page provides a set of utilities to manage the database. You can import and export data as JSON files.</p><h2>Quick Start Guide</h2><ol><li><strong>Import Student Data:</strong> Navigate to the Import page and upload your Canvas and GitHub Classroom CSV files.</li><li><strong>Set Up a Course:</strong> After importing, verify that your course appears under the Courses section.</li><li><strong>Grade Assignments</strong> Click \"Run\" to grade a selected assignment, or \"Run All\" to grade all assignments and generate a grade CSV.</li><li><strong>Download & Upload:</strong> Download the graded CSV and upload it to Canvas.</li></ol><h2>Need More Help?</h2><p>For additional support, check the project documentation.</p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
