// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.819
package web

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func (w *Web) importForm() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<h1>Import Course Data</h1><form hx-post=\"/import\" enctype=\"multipart/form-data\"><div class=\"grid-x\"><div class=\"cell\">Course Name</div><div class=\"cell\"><input type=\"text\" name=\"course\"></div></div><div class=\"grid-x\"><div class=\"cell\">GitHub export</div><div class=\"cell\"><input type=\"file\" name=\"github\" accept=\"text/csv\"></div></div><div class=\"grid-x\"><div class=\"cell\">Canvas export</div><div class=\"cell\"><input type=\"file\" name=\"canvas\" accept=\"text/csv\"></div></div><div class=\"grid-x\"><div class=\"cell\">Assignments JSON</div><div class=\"cell\"><input type=\"file\" name=\"assignments\" accept=\"application/json\"></div></div><button type=\"submit\" class=\"submit button\">Save</button></form>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
